name: Spanish translate

on:
  push:
    branches: ["main"]

jobs:
  translate-1:
      runs-on: ubuntu-latest
      steps:
        - name: Gitbook Translate getting-started
          uses: lyqht/deepl-translate-github-action@v1.0.0
          with: 
            target_languages: es
            input_file_path: getting-started/how-to-guides.md
            output_file_name_prefix: getting-started/
            deepl_api_key: ${{ secrets.DEEPL_API_KEY }}

  translate-2:
     runs-on: ubuntu-latest
     steps:
        - name: Gitbook Translate basics
          uses: lyqht/deepl-translate-github-action@v1.0.0
          with: 
            target_languages: es
            input_file_path: basics/images-and-media.md
            output_file_name_prefix: basics/
            deepl_api_key: ${{ secrets.DEEPL_API_KEY }}

  translate-3:
     runs-on: ubuntu-latest
     steps:
        - name: Gitbook Translate marketing
          uses: lyqht/deepl-translate-github-action@v1.0.0
          with: 
            target_languages: es
            input_file_path: marketing/see-our-work.md
            output_file_name_prefix: marketing/
            deepl_api_key: ${{ secrets.DEEPL_API_KEY }}

